name: Deploy-Infrastructure-Platform
on:
  push:
    branches:
      - master
    paths:
      - 'Infrastructure-Platform/docker-compose.yml'
      - 'Infrastructure-Platform/Makefile'
      - '.github/workflows/**'
      - 'Infrastructure-Platform/*dockerfile'
      - 'Infrastructure-Platform/modules/**'
      - 'Infrastructure-Platform/**.tf'
      - 'Infrastructure-Platform/*.tfvars'
      - 'Infrastructure-Platform/*.txt'

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan       

  terraform_apply:
    environment:
      name: approval
    needs: terraform_plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan
    - name: Terraform_Apply
      run: make run_apply  




